#!/bin/sh
update-mime-database /usr/share/mime/ 
update-desktop-database /usr/share/applications/

for item in $(ls /home)
do
#echo $item
sed -i '/application\/x-ms-dos-executable/d' /home/$item/.config/mimeapps.list	
done

for item in $(ls /home)
do
#echo $item
sed -i '/application\/x-ms-dos-executable/d' /home/$item/.local/applications/mimeapps.list
done

exit 0
